export const SET_AUCTION_DATA = 'SET_AUCTION_DATA';
export const SET_AUCTION_ERROR = 'SET_AUCTION_ERROR';

export const QUICK_BID = 'QUICK_BID';
export const TOGGLE_DESCRIPTION = 'TOGGLE_DESCRIPTION';
