export const FETCH_ITEMS = 'FETCH_ITEMS';
export const FETCH_ITEMS_PENDING = 'FETCH_ITEMS_PENDING';
export const FETCH_ITEMS_FULFILLED = 'FETCH_ITEMS_FULFILLED';
export const FETCH_ITEMS_REJECTED = 'FETCH_ITEMS_REJECTED';
